/**
 * NURSE ANT — Colony Health & Self-Regulation
 * 
 * Biological analog: Nurse ant (Camponotus)
 * Real nurse ants regulate brood temperature, clean dead ants,
 * distribute food, and maintain nest humidity. They are the colony's
 * homeostatic system — keeping everything in balance without any
 * central controller.
 * 
 * Our NurseAnt monitors the HEALTH of the pheromone space itself:
 * 
 * FOUR RESPONSIBILITIES:
 * 
 * 1. STALENESS DETECTION
 *    "Has this location received fresh evidence recently?"
 *    If not, the data is decaying without renewal. Mark as STALE
 *    so harvesters lower confidence and the runtime considers reallocation.
 * 
 * 2. SATURATION DETECTION
 *    "Is this location overwhelmed with too many signals?"
 *    Too many ants at one location = noise. The information value
 *    per signal decreases. Flag as SATURATED so the runtime can
 *    redistribute work to under-served locations.
 * 
 * 3. RESOURCE IMBALANCE DETECTION
 *    "Are some locations getting all the attention while others starve?"
 *    Compare concentration across locations. If the distribution is
 *    heavily skewed, deposit REBALANCE signals to guide the planner.
 * 
 * 4. COLONY HEALTH REPORT
 *    Periodically generates a ColonyHealthReport summarizing
 *    overall swarm health: stale locations, saturated locations,
 *    signal-to-noise ratio, resource balance.
 * 
 * Domain-agnostic. The nurse doesn't know what the signals mean.
 * It monitors structural properties: freshness, volume, distribution.
 * 
 * Memory per ant: ~1KB (tracks all locations — there's only ONE nurse)
 * Cost per tick: ~5ms (scans all locations)
 */

import {
  PheromoneType,
  PheromoneDeposit,
  IPheromoneSpace,
  LocationSnapshot,
  ColonyHealthReport,
} from '../types';

// ─────────────────────────────────────────────
// Nurse Config
// ─────────────────────────────────────────────

export interface NurseAntConfig {
  id: string;
  /** How old the freshest signal can be before the location is STALE (ms). Default: 180000 (3 min) */
  stalenessThresholdMs: number;
  /** Total concentration above which a location is SATURATED. Default: 5.0 */
  saturationThreshold: number;
  /** Minimum concentration for a location to be considered "active". Default: 0.1 */
  activeThreshold: number;
  /** Gini coefficient above which resources are considered imbalanced. Default: 0.6 */
  imbalanceGiniThreshold: number;
  /** Max locations to flag for rebalance per tick. Default: 5 */
  maxRebalanceFlags: number;
}

const DEFAULT_CONFIG: NurseAntConfig = {
  id: 'nurse:primary',
  stalenessThresholdMs: 180_000,
  saturationThreshold: 5.0,
  activeThreshold: 0.1,
  imbalanceGiniThreshold: 0.6,
  maxRebalanceFlags: 5,
};

// ─────────────────────────────────────────────
// Forager signal types (real data signals, not processor/meta)
// ─────────────────────────────────────────────

const FORAGER_SIGNALS: Set<PheromoneType> = new Set([
  PheromoneType.MOMENTUM,
  PheromoneType.DISTRESS,
  PheromoneType.BREAKOUT,
  PheromoneType.FLATLINE,
  PheromoneType.UNUSUAL_ACTIVITY,
  PheromoneType.DRY_UP,
  PheromoneType.ACCUMULATION,
  PheromoneType.FEAR,
  PheromoneType.HYPE,
  PheromoneType.SILENCE,
  PheromoneType.INSIDER_CONFIDENCE,
  PheromoneType.INSIDER_EXIT,
  PheromoneType.INSIDER_CLUSTER,
  PheromoneType.MACRO_SHIFT,
  PheromoneType.MACRO_STABLE,
  PheromoneType.REGIME_CHANGE,
]);

/** Meta / system signals (not real data — generated by processors, guards, etc.) */
const SYSTEM_SIGNALS: Set<PheromoneType> = new Set([
  PheromoneType.CLUSTER_DETECTED,
  PheromoneType.CASCADE_FORMING,
  PheromoneType.ANOMALY,
  PheromoneType.CONVERGENCE,
  PheromoneType.DIVERGENCE,
  PheromoneType.DECOUPLING,
  PheromoneType.CONFUSION,
  PheromoneType.QUARANTINE,
  PheromoneType.VERIFIED,
  PheromoneType.ECHO_CHAMBER,
  PheromoneType.STALE,
  PheromoneType.SATURATED,
  PheromoneType.REBALANCE,
  PheromoneType.HARVEST_READY,
]);

// ─────────────────────────────────────────────
// The Nurse Ant
// ─────────────────────────────────────────────

export class NurseAnt {
  private config: NurseAntConfig;
  private lastHealthReport: ColonyHealthReport | null = null;

  constructor(config: Partial<NurseAntConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * One nurse tick. Scans ALL locations, performs health checks.
   * Returns deposits to make + a colony health report.
   */
  async tick(space: IPheromoneSpace): Promise<{
    deposits: PheromoneDeposit[];
    healthReport: ColonyHealthReport;
  }> {
    const deposits: PheromoneDeposit[] = [];
    const allLocationIds = await space.getLocationIds();

    // Read all location snapshots
    const snapshots = new Map<string, LocationSnapshot>();
    for (const locId of allLocationIds) {
      snapshots.set(locId, await space.read(locId));
    }

    // Filter to entity-level locations (skip meta-locations like MARKET:, SECTOR:)
    const entityLocations: [string, LocationSnapshot][] = [];
    for (const [locId, snap] of snapshots) {
      if (!locId.includes(':')) {
        entityLocations.push([locId, snap]);
      }
    }

    const staleLocations: string[] = [];
    const saturatedLocations: string[] = [];
    const activeLocations: string[] = [];
    const concentrations: { locId: string; concentration: number }[] = [];

    // ─── PER-LOCATION CHECKS ──────────────────

    for (const [locId, snap] of entityLocations) {
      if (snap.totalConcentration < this.config.activeThreshold) continue;
      activeLocations.push(locId);
      concentrations.push({ locId, concentration: snap.totalConcentration });

      // CHECK 1: Staleness
      const staleDeposit = this.checkStaleness(locId, snap);
      if (staleDeposit) {
        deposits.push(staleDeposit);
        staleLocations.push(locId);
      }

      // CHECK 2: Saturation
      const satDeposit = this.checkSaturation(locId, snap);
      if (satDeposit) {
        deposits.push(satDeposit);
        saturatedLocations.push(locId);
      }
    }

    // ─── COLONY-WIDE CHECKS ───────────────────

    // CHECK 3: Resource imbalance
    const rebalanceDeposits = this.checkImbalance(concentrations);
    deposits.push(...rebalanceDeposits);

    const rebalanceTargets = rebalanceDeposits.map(d => ({
      locationId: d.locationId,
      reason: d.strength > 0 ? 'under-served' : 'over-served',
    }));

    // ─── HEALTH REPORT ────────────────────────

    const signalToNoise = this.computeSignalToNoise(entityLocations);
    const healthScore = this.computeHealthScore(
      entityLocations.length,
      activeLocations.length,
      staleLocations.length,
      saturatedLocations.length,
      signalToNoise,
    );

    const healthReport: ColonyHealthReport = {
      timestamp: Date.now(),
      totalLocations: entityLocations.length,
      activeLocations: activeLocations.length,
      staleLocations,
      saturatedLocations,
      rebalanceTargets,
      healthScore,
      signalToNoiseRatio: signalToNoise,
    };

    this.lastHealthReport = healthReport;

    return { deposits, healthReport };
  }

  // ─── CHECK 1: STALENESS ───────────────────────

  /**
   * A location is stale if its freshest FORAGER signal is older than the threshold.
   * Processor signals don't count — they can keep amplifying stale data forever.
   */
  private checkStaleness(locationId: string, snapshot: LocationSnapshot): PheromoneDeposit | null {
    let freshestForagerAge = Infinity;

    for (const sig of snapshot.signals) {
      if (FORAGER_SIGNALS.has(sig.type)) {
        freshestForagerAge = Math.min(freshestForagerAge, sig.peakAge);
      }
    }

    // No fresh evidence signals at all, or all are old
    if (freshestForagerAge > this.config.stalenessThresholdMs) {
      // Strength scales with how stale it is (capped at 0.8)
      const stalenessFactor = Math.min(
        0.8,
        (freshestForagerAge - this.config.stalenessThresholdMs) / this.config.stalenessThresholdMs * 0.4 + 0.3
      );

      return {
        type: PheromoneType.STALE,
        locationId,
        strength: stalenessFactor,
        sourceAntId: this.config.id,
        sourceColony: 'nurse',
        timestamp: Date.now(),
      };
    }

    return null;
  }

  // ─── CHECK 2: SATURATION ──────────────────────

  /**
   * A location is saturated if its total concentration is way above normal.
   * Too many signals = noise. The law of diminishing returns.
   */
  private checkSaturation(locationId: string, snapshot: LocationSnapshot): PheromoneDeposit | null {
    if (snapshot.totalConcentration > this.config.saturationThreshold) {
      const excess = snapshot.totalConcentration / this.config.saturationThreshold;
      return {
        type: PheromoneType.SATURATED,
        locationId,
        strength: Math.min(0.8, (excess - 1) * 0.3 + 0.2),
        sourceAntId: this.config.id,
        sourceColony: 'nurse',
        timestamp: Date.now(),
      };
    }

    return null;
  }

  // ─── CHECK 3: RESOURCE IMBALANCE ──────────────

  /**
   * Uses Gini coefficient to detect if resources are concentrated
   * at a few locations while others are starved.
   * 
   * Deposits REBALANCE at under-served locations (positive strength)
   * so the planner knows where to allocate more reader work.
   */
  private checkImbalance(
    concentrations: { locId: string; concentration: number }[]
  ): PheromoneDeposit[] {
    if (concentrations.length < 3) return []; // Need at least 3 locations

    const values = concentrations.map(c => c.concentration).sort((a, b) => a - b);
    const gini = this.computeGini(values);

    if (gini < this.config.imbalanceGiniThreshold) return []; // Distribution is OK

    // Find under-served locations (bottom quartile of concentration)
    const median = values[Math.floor(values.length / 2)];
    const underServed = concentrations
      .filter(c => c.concentration < median * 0.3)
      .sort((a, b) => a.concentration - b.concentration)
      .slice(0, this.config.maxRebalanceFlags);

    return underServed.map(loc => ({
      type: PheromoneType.REBALANCE,
      locationId: loc.locId,
      strength: Math.min(0.6, (1 - loc.concentration / median) * 0.4 + 0.2),
      sourceAntId: this.config.id,
      sourceColony: 'nurse',
      timestamp: Date.now(),
    }));
  }

  // ─── SIGNAL-TO-NOISE RATIO ────────────────────

  /**
   * Computes signal-to-noise ratio across the colony.
   * "Signal" = evidence-bearing signals. "Noise" = system/meta signals.
   * Higher ratio = healthier colony (real data outweighs internal chatter).
   */
  private computeSignalToNoise(locations: [string, LocationSnapshot][]): number {
    let signalStrength = 0;
    let noiseStrength = 0;

    for (const [, snap] of locations) {
      for (const sig of snap.signals) {
        if (FORAGER_SIGNALS.has(sig.type)) {
          signalStrength += sig.strength;
        } else if (SYSTEM_SIGNALS.has(sig.type)) {
          noiseStrength += sig.strength;
        }
      }
    }

    if (noiseStrength === 0) return signalStrength > 0 ? 10 : 0; // Perfect or empty
    return signalStrength / noiseStrength;
  }

  // ─── HEALTH SCORE ─────────────────────────────

  /**
   * Overall colony health: 0.0 (critical) to 1.0 (optimal).
   * Based on: active ratio, staleness, saturation, signal-to-noise.
   */
  private computeHealthScore(
    total: number,
    active: number,
    stale: number,
    saturated: number,
    snr: number,
  ): number {
    if (total === 0) return 0;

    // Active ratio: what fraction of registered locations are actually producing data
    const activeRatio = active / total;

    // Problem ratio: what fraction of active locations have issues
    const problemRatio = active > 0 ? (stale + saturated) / active : 0;

    // SNR score: signal-to-noise (capped at 1.0 when SNR >= 2.0)
    const snrScore = Math.min(1.0, snr / 2.0);

    // Weighted combination
    const score = (activeRatio * 0.3) + ((1 - problemRatio) * 0.4) + (snrScore * 0.3);

    return Math.max(0, Math.min(1, score));
  }

  // ─── GINI COEFFICIENT ─────────────────────────

  /**
   * Gini coefficient: measure of inequality in a distribution.
   * 0 = perfect equality (all locations have same concentration)
   * 1 = perfect inequality (all concentration at one location)
   */
  private computeGini(sortedValues: number[]): number {
    const n = sortedValues.length;
    if (n === 0) return 0;

    const sum = sortedValues.reduce((a, b) => a + b, 0);
    if (sum === 0) return 0;

    let numerator = 0;
    for (let i = 0; i < n; i++) {
      numerator += (2 * (i + 1) - n - 1) * sortedValues[i];
    }

    return numerator / (n * sum);
  }

  // ─── STATE ────────────────────────────────────

  getId(): string { return this.config.id; }
  getLastHealthReport(): ColonyHealthReport | null { return this.lastHealthReport; }
}
